### ISSUE TITLE
🤔️ 想请教几个问题，感谢 

### ISSUE THREAD

**Issue by aetherwu** [wizardpisces/uni-vue-router#1]
1、部署，是否是将 main.js 里，uniapp 自带的

`app.$mount()`

替换成

```
const router = new Router();

new App({
    router,
    render: h => h(App),
}).$mount();
```

2、部署和初始化以后，是否意味着 uniapp 自带的 pages.js  无效/不起作用了？还是说，Title 等自定义项目依然需要依赖 uniapp 自带系统？

3、现有项目如果要改造，意味着改变目录结构，这个操作会对项目造成什么影响，有什么特别需要注意的地方吗？

4、README 所诉部分
@Watch('$route'
router.beforeEach
@Component export class...
这些代码放在哪里呢？是放在  App.vue 的 onLanuch 里吗？

5、多级子目录页面的 name，是否是按照约定，用 - 多个链接？比如：
/path1/path2/path3 -> path1-path2-path3

6、如果希望对多个 router 配置登录限制，是否有更简洁的写法呢？

以上，如能拨冗答复，非常感谢 🙏

**Comment by wizardpisces** [comment]
首先：感谢你对本框架的信任
问题回答：
1：是
2：本框架没有改变uniapp自带的任何东西，只是做了顶层的封装
3：目录结构按照readme里面约定的改造即可
4：那个是vue  watch的 typescript写法 （vue-property-decorator）
5：参照readme 里面的约定（只需要保证每个目录下有一个index.vue即可）
6：登录限制用 vue-router 的beforeEach即可

其它补充：看你的问题应该是对vue的生态还不是很了解吧？可能需要多花点时间加强对vue的了解

**Comment by aetherwu** [comment]
@wizardpisces 对对，刚开始了解一些。感谢答复 🙏
