### ISSUE TITLE
APP模式支持嵌套路由 router-view这种吗

### ISSUE THREAD

**Issue by Huptzzz** [wizardpisces/uni-vue-router#3]
APP模式支持嵌套路由 router-view这种吗

**Comment by wizardpisces** [comment]
> APP模式支持嵌套路由 router-view这种吗

没试过，不确定，这个工程目前只使用在微信小程序端，uni-app更新的还蛮快，可以去试一下
APP目前建议还是使用flutter等跨端方案，性能会好很多

**Comment by Huptzzz** [comment]
> > APP模式支持嵌套路由 router-view这种吗
> 
> 没试过，不确定，这个工程目前只使用在微信小程序端，uni-app更新的还蛮快，可以去试一下
> APP目前建议还是使用flutter等跨端方案，性能会好很多

行吧 谢谢你  主要用uniapp搞起来效率太快了哈哈

**Comment by wizardpisces** [comment]
> > > APP模式支持嵌套路由 router-view这种吗
> > 
> > 
> > 没试过，不确定，这个工程目前只使用在微信小程序端，uni-app更新的还蛮快，可以去试一下
> > APP目前建议还是使用flutter等跨端方案，性能会好很多
> 
> 行吧 谢谢你 主要用uniapp搞起来效率太快了哈哈

不客气，是得看实际场景的权衡选择
