### ISSUE TITLE
开发设置是否存在问题

### ISSUE THREAD

**Issue by dg489** [wizardpisces/uni-vue-router#5]
我照着你文档上写的方法，创建文件，并在main.js引入，现在报 Cannot find module 'webpack'.webpack需要重新下载？

**Comment by wizardpisces** [comment]
本地有安装webpack么？没有的话需要运行下 
`npm install --save-dev webpack`

**Comment by dg489** [comment]
抱歉，没想到uniapp还得安装webpack。
不过你的修改 src/App.vue 初始化路由、增加 src/router.js这两步的src文件夹是自建的？然后 src/App.vue里面的pages.js是要自建还是读取自带的，App.vue是不是也要创建一个

**Comment by wizardpisces** [comment]
src/App.vue有自动生成吧？ src/router是自建的，pages.js是啥？我的文档里面应该只是提到了pages.json吧

**Comment by dg489** [comment]
> src/App.vue有自动生成吧？ src/router是自建的，pages.js是啥？我的文档里面应该只是提到了pages.json吧
手误，是pages.json。现在没有src目录了，你这个插件我这边跑不起来，装完webpack又报module缺失。

**Comment by wizardpisces** [comment]
把路径搞对应该就可以
原理没变
试着找找现在的onLaunch入口在哪里（也就是之前App.vue里面的内容）

**Comment by dg489** [comment]
Cannot read property 'match' of undefined

**Comment by wizardpisces** [comment]
具体是什么报错？
